Stage2 completed
wh1tef0x-webix/jet-start pull request #2
Opened 2021-04-27 14:23 UTC by wh1tef0x-webix

2021-04-29 12:58 UTC, uladzislaukumakou requested changes

2021-04-29 12:58 UTC, uladzislaukumakou commented on sources/views/tables/index.js
> +		table.eachColumn((id) => {
Весь этот код можно заменить на
`table.setState({filter: {}});`
Этим ты обнулишь все фильтры и значения в хэдере у фильтров тоже обнулится

2021-04-29 15:16 UTC, wh1tef0x-webix commented on sources/views/tables/index.js
> +		table.eachColumn((id) => {
Fixed

2021-04-30 10:01 UTC, uladzislaukumakou approved these changes

2021-04-30 12:58 UTC, HelgaListopad requested changes

2021-04-30 12:58 UTC, HelgaListopad commented on sources/models/contacts.js
> +const dateToStrParser = webix.Date.dateToStr("%Y-%m-%d");
Дата принимается только как "yyyy-mm-dd hh:ii" (валидным будет также "yyyy-mm-dd hh:ii:ss", SQL Datetime)

2021-04-30 12:58 UTC, HelgaListopad commented on sources/models/contacts.js
> +				obj.Birthday = dateToStrParser(obj.Birthday);
Контакт содержит ещё одну дату (StartDate)

2021-04-30 12:58 UTC, HelgaListopad commented on sources/views/contacts/contactEditor.js
> +									labelWidth,
Общие свойства можно перенести в https://docs.webix.com/api__link__ui.form_elementsconfig_config.html
Так они будут примененыт ко всем элементам формы. Если у какого-то виджета те же параметры будут отличаться - его собственные свойства будут приоритетнее.

2021-04-30 12:58 UTC, HelgaListopad commented on sources/views/contacts/contactEditor.js
> +									validateEvent: "key",
У ричселекта нету поля для ввода, поэтому этот validateEvent здесь не очень применим

2021-04-30 12:58 UTC, HelgaListopad commented on sources/views/contacts/contactEditor.js
> +			contactPhoto.refresh();
define+refresh тут можно заменить на [setHTML](https://docs.webix.com/api__ui.template_sethtml.html)

2021-04-30 12:58 UTC, HelgaListopad commented on sources/views/contacts/contactEditor.js
> +			this.show("../info");
тут у тебя info окрывается без параметра => сбрасывается селект в листе

2021-04-30 12:58 UTC, HelgaListopad commented on sources/views/contacts/contactInfo.js
> +					.refresh();
Тоже можно заменить на `setHTML`. 
Результат в случае с полностью составленным HTML будет таким же, но одно действие вместо двух как-то желательнее.

2021-04-30 12:58 UTC, HelgaListopad commented on sources/views/contacts/contactEditor.js
> +			this.show("../info");
От этого страдает вот эта часть ТЗ
https://hackmd.io/@listopad/rk_RV6fez#Scenarios-general

Чтобы получить ID только что добавленного контакта, придётся использовать [waitSave](https://docs.webix.com/api__link__datacollection_waitsave.html)

2021-04-30 12:58 UTC, HelgaListopad commented on sources/views/contacts/index.js
> +			const contactId = url[url.length - 1].params.contact_id;
Всё-таки прямой доступ к URL - не очень стабильное решение (я пропустила это на stage 1, виновата).

Тем более с `length-1`  - это обращение навернётся, если вложенность модулей станет по какой-либо причине глубже.
Я очень советую пересмотреть работу с параметрами и попробовать реализовать всё таким образом, чтобы contact ID хранился/менялся только в этом модуле, а в младших считывался. 
Для изменения параметра в parent view можно из формы и темплейта триггерить событие, передавая в него нужное ID (если нужно выбрать конкретный контакт).

2021-04-30 14:43 UTC, wh1tef0x-webix commented on sources/models/contacts.js
> +const dateToStrParser = webix.Date.dateToStr("%Y-%m-%d");
Исправил в следующем коммите

2021-04-30 14:43 UTC, wh1tef0x-webix commented on sources/models/contacts.js
> +				obj.Birthday = dateToStrParser(obj.Birthday);
Исправил в следующем коммите

2021-04-30 14:45 UTC, wh1tef0x-webix commented on sources/views/contacts/contactEditor.js
> +									labelWidth,
Исправил в следующем коммите

2021-04-30 14:50 UTC, wh1tef0x-webix commented on sources/views/contacts/contactEditor.js
> +									validateEvent: "key",
Исправил в следующем коммите

2021-04-30 14:51 UTC, wh1tef0x-webix commented on sources/views/contacts/contactEditor.js
> +			contactPhoto.refresh();
Исправил в следующем коммите

2021-04-30 14:52 UTC, wh1tef0x-webix commented on sources/views/contacts/contactInfo.js
> +					.refresh();
Исправил в следующем коммите

2021-04-30 15:53 UTC, wh1tef0x-webix commented on sources/views/contacts/contactEditor.js
> +			this.show("../info");
Оно вроде как работало, но я все равно все переделал

2021-04-30 15:53 UTC, wh1tef0x-webix commented on sources/views/contacts/index.js
> +			const contactId = url[url.length - 1].params.contact_id;
Сделал чтобы все было красиво

2021-04-30 16:41 UTC, HelgaListopad commented on sources/views/contacts/contactEditor.js
> +									labelWidth,
margin не подходит - он относится к свойствам layout'a, а inputConfig применяется к полям формы

2021-04-30 16:59 UTC, HelgaListopad commented on sources/views/contacts/contactEditor.js
> +			this.show("../info");
В тестах параметр всё-таки терялся. Но сейчас разве работает?) 
Ты заворачиваешь в waitSave процесс сохранения, но всё ещё никак его не используешь. 
Смотри, в чём проблема. Когда ты пишешь `contactId = contacts.add(values);`, `add` возвращает тебе *временную* локальную айдишку контакта. После этого данные уходят на сервер, и уже оттуда приходит то ID, которое было присвоено ему там. 
Новое ID автоматически заменяет в данных временное (так работает наше сохранение), но к этому моменту у тебя в адресной строке (и параметрах) уже стоит временное значение:
```
/#!/top/contacts/info?contact_id=1619801286550
```
И если ты решишь в этот момент выполнить операции типа edit/delete, получишь ошибку.
waitSave нужен для того, чтобы обернуть в него операцию add, а потом обработать в then ответ сервера (глянь пример в документации, на которую я ссылалась). И вот там уже можно получить актуальную айдишку и переключить selection.

2021-04-30 17:11 UTC, HelgaListopad commented on sources/views/contacts/index.js
> +			const contactId = url[url.length - 1].params.contact_id;
Ну-у, не совсем. 
Не надо использовать getSubView. Это *пока* заманчивое, но очень шаткое решение, которое зависит от иерархии вьюшек однажды не принесёт ничего хорошего.) 
Как правило, API модулей должно быть изолировано от других модулей. Иными словами, методы твоего subView (вклюючая getParam) должны вызываться только в его классе. 

Под "ID хранился/менялся только в этом модуле" я имела в виду перенос параметра id из вложенных subviews на Contacts.
В таком случае, обмениваться параметрами и триггерить нужные действия между модулями можно через app-level события.

2021-04-30 22:00 UTC, wh1tef0x-webix commented on sources/views/contacts/contactEditor.js
> +									labelWidth,
Поправил

2021-04-30 22:00 UTC, wh1tef0x-webix commented on sources/views/contacts/contactEditor.js
> +			this.show("../info");
Упс, я почему-то был уверен что я написал все в then, но на деле оказалось что нет, сейчас все должно быть ок

2021-04-30 22:02 UTC, wh1tef0x-webix commented on sources/views/contacts/index.js
> +			const contactId = url[url.length - 1].params.contact_id;
В самом начале у меня именно так было, но Влад сказал что url вида /top/contact?contact_id=123/info не есть хорошо и попросил сделать чтобы было /top/contact/info?contact_id=123, возможно это я его не так понял, но мне кажется что я правильно его понял

2021-05-01 08:59 UTC, HelgaListopad commented on sources/views/contacts/index.js
> +			const contactId = url[url.length - 1].params.contact_id;
В текущем варианте меня не устраивает реализация.
Важно научиться работать с параметрами/обменом командами между вьюшками без методов, работающих напрямую с иерархией вьюшек (`getSubView`/`getParentView`). 
Готовые варианты описаны [здесь](https://webix.gitbook.io/webix-jet/part-ii-webix-jet-in-details/view-communication#which-way-of-view-communication-to-choose), в твоём случае параметры URL уместны.

В такой ситуации я считаю, что ID контакта как параметр должно храниться там, где мы его меняем. 
Здесь передача его ниже только добавляет пару строчек кода, в то время как получаешь ты его всё равно через тот же `getParam`, независимо от того, на каком уровне этот параметр выставлен. 
Даже если перевести всё с getSubView на события и пробрасывать параметры на subview, это всё равно выглядит как очень лишняя работа. 

Поэтому видимый URL в данном случае вторичен.
Окончательным предложением будет: 
- перенести параметр на Contacts
- отказаться от getSubView, 
- решить проблему внешнего вида урла несколько радикально и использовать [EmptyRouter](https://webix.gitbook.io/webix-jet/part-ii-webix-jet-in-details/routers#4-empty-router)

_Дополнение_
Другим моим предложением было бы использовать [setParam](https://webix.gitbook.io/webix-jet/api/jetview-api/jetview-methods#this-setparam) с третьим флагом `false`, скрывающим параметр, но я заметила нестыковку его поведения с документацией - баг это или недочёт в описании метода, пока предстоит выяснить. 
Оставляй `true`.

2021-05-01 10:56 UTC, wh1tef0x-webix commented on sources/views/contacts/index.js
> +			const contactId = url[url.length - 1].params.contact_id;
Сделал все как ты просила, однако возникло несколько вопросов

1) Полностью отказаться от `getSubView` не получилось, он используется для проверки есть ли subView, это правильное использование? Или стоит отказаться от этого?
2) При использовании `EmptyRouter` страница не сохраняет свое состояние при обновлении (не сохраняется выбранный контакт при просмотре/редактировании, пробовал смотреть почему - url очищается при обновлении страницы), так и должно быть? Или я что-то делаю не так и `EmptyRouter` работает как и должен?

Пока я решил оставить HashRouter, исправлю это если будет нужно, в остальном все исправил

2021-05-01 19:09 UTC, HelgaListopad commented on sources/views/contacts/index.js
> +			const contactId = url[url.length - 1].params.contact_id;
1. Если есть `$subview: true`, оно должно быть (вопрос "какое именно" в parent view по возможности лучше не ставить). Если его в таком случае нет - это вопросы к разработчику.)
Если вопрос о том, инициализировалось ли уже сабвью - обрати внимание на [порядок инита и вызова методов](https://webix.gitbook.io/webix-jet/part-ii-webix-jet-in-details/views#jetview-methods) JetView
2. Да, есть такой эффект. При перезагрузке структура приложения или берётся из урла, или строится дефолтная, или используются другие (уже кастомные) методы сохранения состояния приложения. Если такой вариант тебя не устраивает - оставляй HashRouter. 
Как я и говорила, это для меня это не критично по сравнению с логикой обмена параметрами.

2021-05-01 19:15 UTC, HelgaListopad commented on sources/views/contacts/index.js
>  			this.show("info");
Вот дефолтное subview лучше открывать на ините, а не после селекта (т.е. даже если загрузка контактов занимает время, до первого селекта нужно показать template, пусть даже в нём будет отображаться набор заглушек для undefined-данных). 

После селекта меняется параметр (contact_id), а открытое сейчас сабвью его подхватывает.

2021-05-01 19:18 UTC, HelgaListopad commented on sources/views/contacts/index.js
> +		if (!this.getSubView()) {
Дефолтное сабвью лучше открывать сразу после инита. То есть даже пока данные не пришли, на странице должен быть пустой темплейт с набором "заглушек" для undefined-данных
А уже когда меняется выбранный контакт/contact_id, эти изменения подхватываются сабвью

2021-05-02 08:48 UTC, wh1tef0x-webix commented on sources/views/contacts/index.js
> +			const contactId = url[url.length - 1].params.contact_id;
Полностью избавился от `getSubView`, теперь приложение запускает эвент `contacts:subviewinit` при инициализации subview, проверка на наличие загруженного subview через этот эвент

2021-05-02 08:48 UTC, wh1tef0x-webix commented on sources/views/contacts/index.js
> +		if (!this.getSubView()) {
Уже была подобная возможность, сейчас я ее немного переделал, все должно работать лучше

2021-05-02 14:49 UTC, HelgaListopad commented on sources/views/contacts/index.js
> +			const contactId = url[url.length - 1].params.contact_id;
Если я правильно понимаю, то всё, что даёт эта проверка - позволяет восстановить открытое сабвью после перезагрузки страницы или открыть дефолтное, правильно? 

В принципе, пойдёт, но тут как раз можно обратить внимание на [getURL](https://webix.gitbook.io/webix-jet/api/jetview-api/jetview-methods#this-geturl). 
Что оно умеет и что всё-таки можно тут применить:

> If you call this method from a dynamic subview (as opposed to the top view and a static subview), the method will return only the segments starting from this subview segment

2021-05-02 15:44 UTC, HelgaListopad approved these changes

2021-05-02 15:44 UTC, merged