Stage 3 ready
wh1tef0x-webix/jet-start pull request #3
Opened 2021-05-05 12:40 UTC by wh1tef0x-webix

2021-05-05 13:47 UTC, uladzislaukumakou requested changes

2021-05-05 13:47 UTC, uladzislaukumakou commented on sources/views/form/index.js
> +									click: this._saveClick && this._saveClick.bind(this)
Лучше в initParam это выражение вставь, а то тут уж очень выбивается из общей логики

2021-05-05 14:44 UTC, wh1tef0x-webix commented on sources/views/form/index.js
> +									click: this._saveClick && this._saveClick.bind(this)
Надеюсь я правильно понял что ты имел ввиду, исправил

2021-05-06 08:58 UTC, uladzislaukumakou approved these changes

2021-05-06 09:37 UTC, HelgaListopad requested changes
С появлением возможности редактирования статусов мы попадаем в ситуацию, когда `.getItem(/* status or activity ID */)` может не существовать и `.Value` брать будет не от чего. Добавь по коду необходимые проверки, иначе есть риск сломать много чего в приложении.

2021-05-06 09:37 UTC, HelgaListopad commented on sources/views/contacts/index.js
> +				obj.Status = statuses.getItem(obj.StatusID).Value;
Прежде чем брать Value, добавь здесь проверку на то, что getItem вообще возвращает указанный статус (если его удалили в базе statuses, но он был присвоен где-то в контактах, здесь кинет ошибку).

2021-05-06 10:04 UTC, wh1tef0x-webix commented on sources/views/contacts/index.js
> +				obj.Status = statuses.getItem(obj.StatusID).Value;
Исправил

2021-05-06 10:25 UTC, HelgaListopad commented on sources/views/contacts/index.js
> +				obj.Status = statuses.getItem(obj.StatusID).Value;
Глянь мой общий комментарий на ревью - .Value берётся "опасным" образом в нескольких местах, и "добавь по коду" касалось не только одного метода.
Например сейчас, если ты удалишь существующий activity type, то у тебя навернётся вся таблица

2021-05-06 10:47 UTC, HelgaListopad approved these changes

2021-05-06 10:56 UTC, merged